apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontd-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: backend
  policyTypes:
  - Ingress
  engress:
  - to:
    - podSelector:
        matchLabels:
          run: frontend
  