apiVersion: v1
kind: Deployment 
metdata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx 
  template:
    metdata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: nginx 
        image: nginx:1.14.2
        ports:
        - containerPort: 80          