#kubectl apply -f nameoffile
apiVersion: apps/v1 #all the communciation happen through api
kind: Deployment #we are invoking the deployment api to create a deployment
metadata:
  name: nginx-deployment #i am provding the name of the deployment. 
spec: #master specification #replicas,#selector#template
  replicas: 3 #create three pod
  selector: #to manage those three pod
    matchLabels: #spec.selector.matchlabel field is like a map(key:value) pair
      app: nginx #key value match express
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 #how many pod we can add at a time
      maxUnavailable: 0 #how many pod can be unavaialbe whiel deploying
  template: #inside the pod we need to create container
    metadata:
      labels:
        app: nginx #same label
    spec: #specicifcation about your container
      containers:
      - name: nginx 
        image: nginx:1.14.2
        ports:
        - containerPort: 80          