apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontd-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: frontend
  policyTypes:
  - Egress
  engress:
  - to:
    - podSelector:
        matchLabels:
          run: backend
  