apiVersion: batch/v1
kind: Job
metadata:
  name: twitter-consumer
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 20
  template:
    metadata:
      name: consumer
    spec:
      containers:
      - name: consumer
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["echo 'consuming a message';sleep 5"]
      restartPolicy: OnFailure
