apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls
spec:
  replicas: 1 #if due to some reason the node we are using go down. it should start automatically ina  different machine
  selector:
    matchLabels:
      app: infinite-calls
  template:
    metadata:
      labels:
        app: infinite-calls
    spec:
      containers:
        - name: infinite-calls
          image: busybox #you can run any shell script. 
          command:
          - /bin/sh
          - -c 
          - "while true;do wget -q -O- http://php-apache; done"

