apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gopal
spec:
  replicas: 2 #if due to some reason the node we are using go down. it should start automatically ina  different machine
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql 
          image: mysql:5.6 
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: password
          ports:
            - containerPort: 3306
