apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  storageClassName: hclstorage
  capacity:
    storage: 10Gi #this is thin provisioning
  accessModes:
    - ReadWriteOnce #ReadWritemany #Read
  hostPath:
    path: /mnt/data
  