apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
spec:
  storageClassName: hclstorage #mapping happen through storaclassname
  capacity:
    storage: 3Gi #this is thin provisioning
  accessModes:
    - ReadWriteOnce #ReadWritemany #Read
  hostPath:
    path: /mnt/data
